"""Enumerated register values, transcribed from the integration's option maps."""

from __future__ import annotations

from enum import IntEnum


class InverterStatus(IntEnum):
    """Inverter working status, input register 33095."""

    WAITING = 0
    OPEN_OPERATING = 1
    SOFT_RUN = 2
    GENERATING = 3
    BYPASS_INVERTER_RUNNING = 4
    BYPASS_INVERTER_SYNC = 5
    BYPASS_GRID_RUNNING = 6
    NORMAL_RUNNING = 15
    GRID_OFF = 4100
    GRID_OVERVOLTAGE = 4112
    GRID_UNDERVOLTAGE = 4113
    GRID_OVERFREQUENCY = 4114
    GRID_UNDERFREQUENCY = 4115
    GRID_REVERSE_CURRENT = 4116
    NO_GRID = 4117
    GRID_UNBALANCED = 4118
    GRID_FREQUENCY_FLUCTUATION = 4119
    GRID_OVERCURRENT = 4120
    GRID_CURRENT_SAMPLING_ERROR = 4121
    DC_OVERVOLTAGE = 4128
    DC_BUS_OVERVOLTAGE = 4129
    DC_BUS_UNBALANCED = 4130
    DC_BUS_UNDERVOLTAGE = 4131
    DC_BUS_UNBALANCED_2 = 4132
    DC_CHANNEL_A_OVERCURRENT = 4133
    DC_CHANNEL_B_OVERCURRENT = 4134
    DC_INTERFERENCE = 4135
    DC_REVERSE = 4136
    PV_MIDPOINT_GROUNDING = 4137
    GRID_INTERFERENCE_PROTECTION = 4144
    DSP_INITIAL_PROTECTION = 4145
    OVER_TEMPERATURE_PROTECTION = 4146
    PV_INSULATION_FAULT = 4147
    LEAKAGE_CURRENT_PROTECTION = 4148
    RELAY_CHECK_PROTECTION = 4149
    DSP_B_PROTECTION = 4150
    DC_INJECTION_PROTECTION = 4151
    UNDERVOLTAGE_12V_FAULTY = 4152
    LEAKAGE_CURRENT_CHECK_PROTECTION = 4153
    UNDER_TEMPERATURE_PROTECTION = 4154
    AFCI_CHECK_FAULT = 4160
    AFCI_FAULT = 4161
    DSP_CHIP_SRAM_FAULT = 4162
    DSP_CHIP_FLASH_FAULT = 4163
    DSP_CHIP_PC_POINTER_FAULT = 4164
    DSP_CHIP_REGISTER_FAULT = 4165
    GRID_INTERFERENCE_PROTECTION_02 = 4166
    GRID_CURRENT_SAMPLING_ERROR_2 = 4167  # Grid Current Sampling Error
    IGBT_OVERCURRENT = 4168
    GRID_TRANSIENT_OVERCURRENT = 4176
    BATTERY_HARDWARE_OVERVOLTAGE_FAULT = 4177
    LLC_HARDWARE_OVERCURRENT = 4178
    BATTERY_OVERVOLTAGE = 4179
    BATTERY_UNDERVOLTAGE = 4180
    BATTERY_NOT_CONNECTED = 4181
    BACKUP_OVERVOLTAGE = 4182
    BACKUP_OVERLOAD = 4183
    DSP_SELFCHECK_ERROR = 4184
    FAIL_SAFE = 8208
    METER_COM_FAIL = 8209
    BATTERY_COM_FAIL = 8210
    DSP_COM_FAIL = 8212
    BMS_ALARM = 8213
    BATNAME_FAIL = 8214
    BMS_ALARM_2 = 8215
    DRM_CONNECT_FAIL = 8216
    METER_SELECT_FAIL = 8217
    LEAD_ACID_BATTERY_HIGH_TEMP = 8224
    LEAD_ACID_BATTERY_LOW_TEMP = 8225
    GRID_SURGE = 61456
    FAN_FAULT = 61457


class EnergyStorageMode3Slot(IntEnum):
    """Storage mode word of the three-slot protocol (holding 43110)."""

    SELF_USE_NO_GRID_CHARGING = 1
    TIMED_CHARGE_DISCHARGE_NO_GRID_CHARGING = 3
    BACKUP_RESERVE_NO_GRID_CHARGING = 17
    SELF_USE_NO_TIMED_CHARGE_DISCHARGE = 33
    SELF_USE = 35
    OFF_GRID_MODE = 37
    BATTERY_AWAKEN = 41
    BATTERY_AWAKEN_TIMED_CHARGE_DISCHARGE = 43
    BACKUP_RESERVE_NO_TIMED_CHARGE_DISCHARGE = 49
    BACKUP_RESERVE = 51
    FEED_IN_PRIORITY_NO_GRID_CHARGING = 64
    FEED_IN_PRIORITY_NO_TIMED_CHARGE_DISCHARGE = 96
    FEED_IN_PRIORITY = 98


class EnergyStorageMode6Slot(IntEnum):
    """Storage mode word of the six-slot protocol (holding 43110)."""

    SELF_USE_NO_GRID_CHARGING = 1
    BACKUP_RESERVE_NO_GRID_CHARGING = 17
    SELF_USE = 33
    OFF_GRID_MODE = 37
    BATTERY_AWAKEN = 41
    BACKUP_RESERVE = 49
    FEED_IN_PRIORITY_NO_GRID_CHARGING = 64
    FEED_IN_PRIORITY = 96


class PowerSwitch(IntEnum):
    """Inverter on/off command, holding register 43007."""

    ON = 190
    OFF = 222


class BackflowSwitchX1(IntEnum):
    """Export limit switch on single-phase inverters, holding register 43073."""

    OFF = 0
    ON = 16


class BackflowSwitchX3(IntEnum):
    """Export limit switch on three-phase inverters, holding register 43073."""

    OFF_BALANCED_OUTPUT = 0
    ON_BALANCED_OUTPUT = 16
    OFF_UNBALANCED_OUTPUT = 64
    ON_UNBALANCED_OUTPUT = 80


class BatteryOverride(IntEnum):
    """Forced charge/discharge override, holding register 43135."""

    OFF = 0
    FORCE_CHARGE = 1
    FORCE_DISCHARGE = 2
